import type { Threat } from "../types";

interface ReportParams {
  status: "safe" | "danger" | null;
  threats: Threat[];
  targetLat: number;
  targetLon: number;
  targetAlt: number;
  inclination: number;
  launchTime: string;
  checkedCount: number | null;
}

export function generateReport(params: ReportParams) {
  const { status, threats, targetLat, targetLon, targetAlt, inclination, launchTime, checkedCount } = params;

  const lines = [
    "OPAS — COLLISION RISK REPORT",
    "=".repeat(50),
    `Generated: ${new Date().toUTCString()}`,
    `Status:    ${status?.toUpperCase()}${threats.length > 0 ? ` — ${threats.length} risk(s)` : ""}`,
    "",
    "MISSION PARAMETERS",
    "-".repeat(50),
    `Launch Site:      ${targetLat}°, ${targetLon}°`,
    `Target Altitude:  ${targetAlt} km`,
    `Inclination:      ${inclination}°`,
    `Launch Time:      ${launchTime ? new Date(launchTime).toUTCString() : "Not specified"}`,
    `Objects Checked:  ${checkedCount?.toLocaleString() ?? "N/A"}`,
    "",
    `COLLISION RISKS (${threats.length})`,
    "-".repeat(50),
  ];

  threats.forEach((t, i) => {
    lines.push("");
    lines.push(`[${i + 1}] ${t.name}`);
    lines.push(`    NORAD ID:          ${t.norad_id}`);
    lines.push(`    Miss Distance:     ${t.distance_km.toFixed(3)} km`);
    lines.push(`    Debris Altitude:   ${t.altitude_km.toFixed(1)} km${t.altitude_diff_km != null ? ` (Δ ${t.altitude_diff_km.toFixed(1)} km)` : ""}`);
    lines.push(`    Debris Position:   ${t.location.coordinates[1].toFixed(4)}°, ${t.location.coordinates[0].toFixed(4)}°`);
    if (t.severity) {
      lines.push(`    Severity:          ${t.severity}${t.collision_probability != null ? ` (Pc: ${t.collision_probability.toExponential(2)})` : ""}`);
    }
    if (t.position_uncertainty_km != null) {
      lines.push(`    Pos. Uncertainty:  ${t.position_uncertainty_km.toFixed(2)} km`);
    }
    if (t.closest_approach_time) {
      lines.push(`    Closest Approach:  ${new Date(t.closest_approach_time).toUTCString()}`);
    }
    if (t.approach_location) {
      lines.push(`    Approach Location: ${t.approach_location.lat.toFixed(4)}°, ${t.approach_location.lon.toFixed(4)}°`);
    }
  });

  lines.push("");
  lines.push("=".repeat(50));
  lines.push("Generated by OPAS (Orbital Proximity Alert System)");

  const blob = new Blob([lines.join("\n")], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `opas-report-${new Date().toISOString().slice(0, 10)}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}
